// Exception Handling
/* The try statement allows you to define a block of code to be tested for errors while it is being executed.
The 'throw' keyword throws an exception when a problem is detected, which lets us create a custom error.
The 'catch' statement allows you to define a block of code to be executed, if an error occurs in the try block.
The 'try' and 'catch' keywords come in pairs: */

/* try {
  // Block of code to try
  throw exception; // Throw an exception when a problem arise
}
catch () {
  // Block of code to handle errors
} */


